import AutoAwesomeOutlinedIcon from "@mui/icons-material/AutoAwesomeOutlined";
import Paper from "@mui/material/Paper";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import type { AnalyticsBusinessSummary } from "../../services/dashboardApi";
import EmptyState from "../common/EmptyState";

type AnalyticsSummaryPanelProps = {
  summary: AnalyticsBusinessSummary | null;
};

export default function AnalyticsSummaryPanel({ summary }: AnalyticsSummaryPanelProps) {
  if (!summary) {
    return (
      <Paper variant="outlined" sx={{ p: 3, height: "100%" }}>
        <EmptyState message="Analytics service summary is unavailable. Dashboard data remains available from the Node API." />
      </Paper>
    );
  }

  return (
    <Paper variant="outlined" sx={{ p: 3, height: "100%" }}>
      <Stack spacing={2}>
        <Stack direction="row" spacing={1.25} alignItems="center">
          <AutoAwesomeOutlinedIcon color="primary" />
          <Stack>
            <Typography variant="h6" fontWeight={800}>
              Analytics Summary
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Generated by the FastAPI analytics service from CSV marts.
            </Typography>
          </Stack>
        </Stack>

        <Typography>{summary.summary}</Typography>

        <Stack spacing={0.75}>
          <Typography variant="subtitle2" fontWeight={800}>
            Highlights
          </Typography>
          {summary.highlights.slice(0, 3).map((highlight) => (
            <Typography key={highlight} variant="body2" color="text.secondary">
              {highlight}
            </Typography>
          ))}
        </Stack>

        {summary.risks.length > 0 && (
          <Stack spacing={0.75}>
            <Typography variant="subtitle2" fontWeight={800}>
              Risks to review
            </Typography>
            {summary.risks.slice(0, 3).map((risk) => (
              <Typography key={risk} variant="body2" color="text.secondary">
                {risk}
              </Typography>
            ))}
          </Stack>
        )}
      </Stack>
    </Paper>
  );
}
